### ISSUE TITLE
Can't connect to HA via SSH

### ISSUE THREAD

**Issue by DawMaster** [roth-m/miioclient-mqtt#11]
Hi,
thanks for your work it's amazing :-) But still I have problem with connect to HA via miio_client. When I start gateway than no miio_client process running (only hkbridge, dropbear, wpa_supplicant,dhclient). If I run hacked miio_client manually than I will see in processes but still not working with HA. Do you have any Idea what i do wrong?
It is Aqara hub chinesse with homekit (lumi.gateway.aqhm01)
![after_start](https://user-images.githubusercontent.com/12236083/84996852-1b314280-b14e-11ea-8e71-5b478c6ebef1.png)
![default](https://user-images.githubusercontent.com/12236083/84996855-1c626f80-b14e-11ea-98a8-f0e4a840ef98.png)

**Comment by roth-m** [comment]
Using the modded miio_client the protocol used is the one from the vendor (Aqara) thus the miio implementation in HA won't talk to it.
