### ISSUE TITLE
After restarting miio_client, miioclient_mqtt.py doesn't receive events anymore

### ISSUE THREAD

**Issue by mapbuh** [roth-m/miioclient-mqtt#5]
If miio_client on the hub is restarted, miioclient_mqtt.py doesn't receive any events after that.
Interesting enough, if you connect two miioclient_mqtty.py to miio_client - only one of them will receive the events

**Comment by roth-m** [comment]
If restarted, the modified miio_client will not know any client. Once 1 message is received by one client (ie:1 PING message), it will register it as a client and start to broadcast gateway messages to it.
So a setup with 2 miioclient_mqtt "connected" (it's UDP so it is state less) to the modified miio_client SHOULD work.
