### ISSUE TITLE
miio_client: How to start it automatically on Gateway restart

### ISSUE THREAD

**Issue by scottie34** [roth-m/miioclient-mqtt#7]
Is there a way to start it automatically when the gateway is rebooted.
I currently need to connect via ssh to run the following each time the gateway has been rebooted:
`killall miio_client && nohup /home/root/hack/miio_client &`

Thanks for your work BTW.

**Comment by roth-m** [comment]
Hi,

You can add it to /etc/rc.local
You should add at least a 30 seconds delay before launching the new miio_client as the original one will setup Wifi.

Best

**Comment by Griizly** [comment]
Hi, sorry to reply here but I don't know where to type the commmand in the rc.local ( i'm not good at linux )
Under which line should I put it ?
Thanks !
![Screenshot_2020-04-09-23-27-46-086_com sonelli juicessh](https://user-images.githubusercontent.com/20046947/78942379-e489dc80-7ab9-11ea-9ef9-f44133e59d67.jpg)

**Comment by Griizly** [comment]
i've added it juste after the last #fi now my gateway is stuck with white led and doesn't connect to the wifi :s Here is the 2 lines of code i've added:
sleep 1m
killall miio_client && nohup /home/root/hack/miio_client &

**Comment by roth-m** [comment]
It should be added just *above* fac_test .
